import { connectDB } from "./db";
import Mentor from "@/models/Mentor";

export const initialMentors = [
  {
    name: "Anubhav Mittal",
    role: "Full Stack Developer",
    company: "Google",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059102/HomeMentorImage_9_c0qrmh.webp",
    category: "Web Development",
    skills: ["React", "Node.js", "MongoDB", "Next.js", "TypeScript"],
    rating: 4.9,
    reviews: 111,
    exp: "5+ years",
    experienceYears: 5,
    isPopular: true,
    featuredOrder: 1,
    bio: "Senior Full Stack Engineer with 5+ years of experience building high-scale distributed web applications and guiding hundreds of developers into top tech roles.",
    about: "I specialize in modern JavaScript/TypeScript ecosystems, architecture, React, Next.js, Node.js, and helping developers crack tech interviews and level up their engineering careers.",
    hourlyRate: 65,
    available: true,
    socialLinks: {
      linkedin: "https://linkedin.com",
      github: "https://github.com",
    },
  },
  {
    name: "Chitrakshi Verma",
    role: "Data Scientist",
    company: "Flipkart",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059110/HomeMentorImage_6_vmrjbo.webp",
    category: "Data Science",
    skills: ["Python", "ML", "AI", "TensorFlow", "Pandas"],
    rating: 4.8,
    reviews: 96,
    exp: "2+ years",
    experienceYears: 2,
    isPopular: true,
    featuredOrder: 2,
    bio: "Data Scientist passionate about Machine Learning, AI models, and turning messy data into predictive insights.",
    about: "Hands-on mentor helping aspiring data scientists build strong portfolios, master Python/ML pipelines, and land high-paying analytics roles.",
    hourlyRate: 55,
    available: true,
    socialLinks: {
      linkedin: "https://linkedin.com",
      github: "https://github.com",
    },
  },
  {
    name: "Gitakshi Sharma",
    role: "Product Designer",
    company: "Nvidia",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059105/HomeMentorImage_8_mgrhux.webp",
    category: "Design",
    skills: ["UI/UX", "Figma", "Adobe XD", "Prototyping", "Design Systems"],
    rating: 4.9,
    reviews: 143,
    exp: "6+ years",
    experienceYears: 6,
    isPopular: true,
    featuredOrder: 3,
    bio: "Lead Product Designer creating intuitive user experiences and design systems for enterprise applications.",
    about: "I help designers elevate their craft, build stand-out portfolios, master Figma workflows, and successfully navigate product design hiring processes.",
    hourlyRate: 70,
    available: true,
    socialLinks: {
      linkedin: "https://linkedin.com",
    },
  },
  {
    name: "Akshika G",
    role: "Career Coach",
    company: "Microsoft",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059111/HomeMentorImage_2_qrjsff.webp",
    category: "Career Guidance",
    skills: ["Resume", "Interview", "Growth", "Negotiation", "Leadership"],
    rating: 4.8,
    reviews: 79,
    exp: "6+ years",
    experienceYears: 6,
    isPopular: true,
    featuredOrder: 4,
    bio: "Senior HR & Career Coach with expertise in mock interviews, resume optimization, and executive career transitions.",
    about: "Dedicated to helping early and mid-career professionals craft standout resumes, excel in behavioral and technical interviews, and negotiate winning compensation packages.",
    hourlyRate: 50,
    available: true,
    socialLinks: {
      linkedin: "https://linkedin.com",
    },
  },
  {
    name: "Radhika Sharma",
    role: "Marketing Strategist",
    company: "IBM",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059103/HomeMentorImage_4_k2nujc.webp",
    category: "Marketing",
    skills: ["SEO", "Growth Marketing", "Content Strategy", "Social Media"],
    rating: 4.9,
    reviews: 64,
    exp: "4+ years",
    experienceYears: 4,
    isPopular: true,
    featuredOrder: 5,
    bio: "Growth Marketer helping brands scale from 0 to 1M+ organic reach through data-driven campaigns.",
    about: "Mentoring marketers on modern inbound strategies, performance marketing, product-led growth, and brand positioning.",
    hourlyRate: 45,
    available: true,
    socialLinks: {
      linkedin: "https://linkedin.com",
    },
  },
  {
    name: "Siddharth Rao",
    role: "Business Consultant",
    company: "Amazon",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059102/HomeMentorImage_9_c0qrmh.webp",
    category: "Business",
    skills: ["Strategy", "Operations", "Product Management", "Financial Modeling"],
    rating: 4.9,
    reviews: 88,
    exp: "7+ years",
    experienceYears: 7,
    isPopular: true,
    featuredOrder: 6,
    bio: "Business operations lead and startup advisor specializing in scaling product lines and business models.",
    about: "Providing actionable business strategy, startup advisory, financial planning, and operational excellence coaching.",
    hourlyRate: 75,
    available: true,
    socialLinks: {
      linkedin: "https://linkedin.com",
    },
  },
  {
    name: "Vikram Malhotra",
    role: "Cloud & DevOps Architect",
    company: "Oracle",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059110/HomeMentorImage_6_vmrjbo.webp",
    category: "Cloud Computing",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD", "Terraform"],
    rating: 4.8,
    reviews: 52,
    exp: "8+ years",
    experienceYears: 8,
    isPopular: true,
    featuredOrder: 7,
    bio: "DevOps specialist focused on cloud infrastructure automation, reliability, and modern continuous deployment.",
    about: "Guiding software engineers into high-demand DevOps and Cloud Engineering roles with hands-on AWS & Kubernetes projects.",
    hourlyRate: 80,
    available: true,
    socialLinks: {
      linkedin: "https://linkedin.com",
      github: "https://github.com",
    },
  },
  {
    name: "Pooja Hegde",
    role: "AI & ML Specialist",
    company: "Meta",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059105/HomeMentorImage_8_mgrhux.webp",
    category: "AI & Machine Learning",
    skills: ["Deep Learning", "NLP", "PyTorch", "Computer Vision", "LLMs"],
    rating: 5.0,
    reviews: 120,
    exp: "5+ years",
    experienceYears: 5,
    isPopular: true,
    featuredOrder: 8,
    bio: "AI Researcher working on large language models, generative AI architectures, and neural networks.",
    about: "Empowering developers to master Deep Learning, fine-tune open source LLMs, and build production AI applications.",
    hourlyRate: 90,
    available: true,
    socialLinks: {
      linkedin: "https://linkedin.com",
      github: "https://github.com",
    },
  },
  {
    name: "Rohan Kulkarni",
    role: "Frontend Engineer",
    company: "Uber",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1784985125/HomeBannerTestimonialPerson_1_vtpgtb.webp",
    category: "Web Development",
    skills: ["React", "TypeScript", "TailwindCSS", "Next.js", "Redux"],
    rating: 4.9,
    reviews: 82,
    exp: "4+ years",
    experienceYears: 4,
    isPopular: false,
    featuredOrder: 9,
    bio: "Senior Frontend Engineer specializing in high performance web applications and accessible UI components.",
    about: "Helping frontend developers master advanced React patterns, TypeScript best practices, and frontend system architecture.",
    hourlyRate: 60,
    available: true,
  },
  {
    name: "Sneha Nair",
    role: "Cyber Security Analyst",
    company: "Cisco",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1784985126/HomeBannerTestimonialPerson_2_vw8rwa.webp",
    category: "Cyber Security",
    skills: ["Network Security", "Ethical Hacking", "SOC", "SIEM", "Penetration Testing"],
    rating: 4.8,
    reviews: 47,
    exp: "5+ years",
    experienceYears: 5,
    isPopular: false,
    featuredOrder: 10,
    bio: "Certified Information Systems Security Professional protecting enterprise infrastructure and mentoring cybersecurity enthusiasts.",
    about: "Practical hands-on training for SOC analysis, vulnerability assessment, threat intelligence, and security certification exams.",
    hourlyRate: 70,
    available: true,
  },
  {
    name: "Aditya Roy",
    role: "Mobile App Developer",
    company: "Swiggy",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1784985126/HomeBannerTestimonialPerson_3_ps7s1s.webp",
    category: "App Development",
    skills: ["Flutter", "React Native", "iOS", "Android", "Dart"],
    rating: 4.9,
    reviews: 73,
    exp: "3+ years",
    experienceYears: 3,
    isPopular: false,
    featuredOrder: 11,
    bio: "Cross-platform mobile architect with over 10+ published apps with 5M+ active downloads.",
    about: "Guiding developers through state management in Flutter/React Native, app store deployment, and smooth animations.",
    hourlyRate: 55,
    available: true,
  },
  {
    name: "Kavita Sen",
    role: "UI/UX & Brand Designer",
    company: "Adobe",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1784985124/HomeBannerTestimonialPerson_4_xiafuw.webp",
    category: "Design",
    skills: ["User Research", "Wireframing", "Figma", "Design Thinking", "Branding"],
    rating: 5.0,
    reviews: 91,
    exp: "7+ years",
    experienceYears: 7,
    isPopular: false,
    featuredOrder: 12,
    bio: "Lead Experience Designer crafting user-centric digital products and brand visual identities.",
    about: "Portfolio critiques, storytelling in design interviews, and building scalable UI component libraries.",
    hourlyRate: 65,
    available: true,
  },
  {
    name: "Arjun Mehta",
    role: "Backend Architect",
    company: "Goldman Sachs",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059102/HomeMentorImage_9_c0qrmh.webp",
    category: "Web Development",
    skills: ["Java", "Spring Boot", "Microservices", "Kafka", "PostgreSQL"],
    rating: 4.9,
    reviews: 104,
    exp: "8+ years",
    experienceYears: 8,
    isPopular: false,
    featuredOrder: 13,
    bio: "Fintech backend engineer building low latency transactional systems and resilient microservices architectures.",
    about: "Mentoring backend engineers on distributed systems, databases, caching strategies, and system design interviews.",
    hourlyRate: 85,
    available: true,
  },
  {
    name: "Meera Joshi",
    role: "Product Manager",
    company: "Zomato",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059110/HomeMentorImage_6_vmrjbo.webp",
    category: "Business",
    skills: ["Product Strategy", "Agile", "User Analytics", "Roadmapping", "A/B Testing"],
    rating: 4.8,
    reviews: 62,
    exp: "5+ years",
    experienceYears: 5,
    isPopular: false,
    featuredOrder: 14,
    bio: "Group Product Manager leading core discovery and customer retention teams.",
    about: "Helping aspiring PMs transition into product roles, build strong PRDs, and master metric-driven execution.",
    hourlyRate: 70,
    available: true,
  },
  {
    name: "Tanya Singhal",
    role: "Data Engineer",
    company: "Snowflake",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059105/HomeMentorImage_8_mgrhux.webp",
    category: "Data Science",
    skills: ["SQL", "Apache Spark", "Airflow", "Snowflake", "dbt"],
    rating: 4.9,
    reviews: 58,
    exp: "4+ years",
    experienceYears: 4,
    isPopular: false,
    featuredOrder: 15,
    bio: "Data pipeline engineer designing robust ETL workflows and enterprise data warehouses.",
    about: "Guiding engineers through advanced SQL modeling, data pipeline orchestration, and cloud analytics platforms.",
    hourlyRate: 65,
    available: true,
  },
  {
    name: "Manish Agarwal",
    role: "Cloud Security Engineer",
    company: "Palo Alto Networks",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059111/HomeMentorImage_2_qrjsff.webp",
    category: "Cyber Security",
    skills: ["Cloud Security", "AWS IAM", "Compliance", "Zero Trust", "DevSecOps"],
    rating: 4.7,
    reviews: 39,
    exp: "6+ years",
    experienceYears: 6,
    isPopular: false,
    featuredOrder: 16,
    bio: "DevSecOps engineer securing multi-cloud environments and automating compliance guardrails.",
    about: "Hands-on guidance on container security, IAM privilege policies, and secure CI/CD pipelines.",
    hourlyRate: 75,
    available: true,
  },
  {
    name: "Divya Balan",
    role: "Social Media & Growth Lead",
    company: "Nykaa",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059103/HomeMentorImage_4_k2nujc.webp",
    category: "Marketing",
    skills: ["Influencer Marketing", "Instagram Ads", "Copywriting", "Viral Content"],
    rating: 4.9,
    reviews: 87,
    exp: "3+ years",
    experienceYears: 3,
    isPopular: false,
    featuredOrder: 17,
    bio: "Growth strategist driving engagement, brand virality, and conversion through organic storytelling.",
    about: "Actionable coaching on high-converting social campaigns, creative direction, and audience growth funnels.",
    hourlyRate: 40,
    available: true,
  },
  {
    name: "Karan Johar",
    role: "iOS Developer",
    company: "Apple",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1784985125/HomeBannerTestimonialPerson_1_vtpgtb.webp",
    category: "App Development",
    skills: ["Swift", "SwiftUI", "Combine", "CoreData", "TestFlight"],
    rating: 5.0,
    reviews: 95,
    exp: "7+ years",
    experienceYears: 7,
    isPopular: false,
    featuredOrder: 18,
    bio: "Senior iOS developer crafting fluid native applications and delightful Apple platform experiences.",
    about: "Deep dives into SwiftUI architectures, memory profiling, App Store approval guidelines, and iOS interviews.",
    hourlyRate: 80,
    available: true,
  },
  {
    name: "Alok Gupta",
    role: "Machine Learning Engineer",
    company: "Intel",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059102/HomeMentorImage_9_c0qrmh.webp",
    category: "AI & Machine Learning",
    skills: ["Computer Vision", "OpenCV", "TensorRT", "C++", "Edge AI"],
    rating: 4.8,
    reviews: 51,
    exp: "5+ years",
    experienceYears: 5,
    isPopular: false,
    featuredOrder: 19,
    bio: "Specializing in hardware-accelerated deep learning inference and embedded computer vision pipelines.",
    about: "Mentoring on model quantization, OpenCV pipelines, C++ inference deployment, and ML engineering.",
    hourlyRate: 70,
    available: true,
  },
  {
    name: "Neha Rastogi",
    role: "Executive Leadership Coach",
    company: "Deloitte",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1784985126/HomeBannerTestimonialPerson_2_vw8rwa.webp",
    category: "Career Guidance",
    skills: ["Executive Presence", "Public Speaking", "Team Management", "Conflict Resolution"],
    rating: 4.9,
    reviews: 115,
    exp: "10+ years",
    experienceYears: 10,
    isPopular: false,
    featuredOrder: 20,
    bio: "Executive coach mentoring tech leads, directors, and aspiring leaders to step into managerial excellence.",
    about: "Personalized coaching on communicating with influence, leading diverse teams, and accelerating executive promotions.",
    hourlyRate: 95,
    available: true,
  },
  {
    name: "Rajesh Kannan",
    role: "Solutions Architect",
    company: "Microsoft",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1784985126/HomeBannerTestimonialPerson_3_ps7s1s.webp",
    category: "Cloud Computing",
    skills: ["Azure", "Enterprise Architecture", "Disaster Recovery", "Kubernetes", "Cost Optimization"],
    rating: 4.9,
    reviews: 69,
    exp: "9+ years",
    experienceYears: 9,
    isPopular: false,
    featuredOrder: 21,
    bio: "Principal Cloud Solutions Architect helping enterprises modernize their digital infrastructure on Azure and multi-cloud.",
    about: "Cloud architecture reviews, cost optimization strategies, and preparation for Azure Solutions Architect certifications.",
    hourlyRate: 85,
    available: true,
  },
  {
    name: "Sonali Patel",
    role: "SEO & Content Lead",
    company: "HubSpot",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1784985124/HomeBannerTestimonialPerson_4_xiafuw.webp",
    category: "Marketing",
    skills: ["Technical SEO", "Content Marketing", "Keyword Strategy", "Google Analytics 4"],
    rating: 4.8,
    reviews: 43,
    exp: "4+ years",
    experienceYears: 4,
    isPopular: false,
    featuredOrder: 22,
    bio: "SEO lead scaling SaaS organic traffic through technical site health, topic clusters, and content distribution.",
    about: "Hands-on guidance on technical SEO audits, site speed optimization, schema markup, and content strategy.",
    hourlyRate: 50,
    available: true,
  },
  {
    name: "Harsh Vardhan",
    role: "Full Stack Web3 Developer",
    company: "Polygon",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059102/HomeMentorImage_9_c0qrmh.webp",
    category: "Web Development",
    skills: ["Solidity", "Ethers.js", "React", "Smart Contracts", "Next.js"],
    rating: 4.9,
    reviews: 38,
    exp: "3+ years",
    experienceYears: 3,
    isPopular: false,
    featuredOrder: 23,
    bio: "Smart contract developer building decentralized finance applications and secure blockchain infrastructure.",
    about: "Teaching blockchain fundamentals, smart contract security, React frontend integrations, and Web3 career tracks.",
    hourlyRate: 65,
    available: true,
  },
  {
    name: "Shruti Deshmukh",
    role: "Business Analyst",
    company: "McKinsey & Company",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059110/HomeMentorImage_6_vmrjbo.webp",
    category: "Business",
    skills: ["Business Modeling", "Market Analysis", "Tableau", "Case Interviews"],
    rating: 4.9,
    reviews: 77,
    exp: "5+ years",
    experienceYears: 5,
    isPopular: false,
    featuredOrder: 24,
    bio: "Management consultant helping global companies solve complex operational and strategic challenges.",
    about: "Case interview frameworks, financial storytelling with Tableau/Excel, and consulting problem-solving mastery.",
    hourlyRate: 75,
    available: true,
  },
  {
    name: "Gaurav Sen",
    role: "System Design & Distributed Systems",
    company: "Atlassian",
    image: "https://res.cloudinary.com/dkbelrldw/image/upload/v1785059105/HomeMentorImage_8_mgrhux.webp",
    category: "Web Development",
    skills: ["System Design", "High Scale", "Distributed Caching", "Load Balancing", "Golang"],
    rating: 5.0,
    reviews: 160,
    exp: "9+ years",
    experienceYears: 9,
    isPopular: true,
    featuredOrder: 25,
    bio: "Staff Engineer helping engineers build scalable systems and master high-level and low-level system design.",
    about: "In-depth system design mock interviews, rate limiting, CAP theorem in practice, and scaling systems to millions of concurrent users.",
    hourlyRate: 100,
    available: true,
  },
];

export async function ensureSeedData() {
  try {
    await connectDB();
    const count = await Mentor.countDocuments();
    if (count < 22) {
      console.log(`Updating / seeding mentors to MongoDB (current count: ${count})...`);
      await Mentor.deleteMany({});
      await Mentor.insertMany(initialMentors);
      console.log(`Seeded ${initialMentors.length} mentors successfully!`);
    }
  } catch (error) {
    console.error("Error in ensureSeedData:", error);
  }
}
